language: php
php:
  - '7.0'
  - hhvm-3.14
  
dist: trusty
sudo: required
  
before_script:
  - composer install
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then sudo bash -c 'echo "hhvm.php7.scalar_types = true" >> /etc/hhvm/php.ini'; fi